[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "http://169.58.1.141:3001"

[[redirects]]
  from   = "/api/*"
  to     = "http://169.58.1.141:3001/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
